# Generated by Django 5.1.5 on 2025-02-05 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramChair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('program', models.CharField(max_length=255)),
                ('appointment_date', models.DateField()),
                ('contact_number', models.CharField(max_length=20)),
                ('office_location', models.CharField(max_length=255)),
                ('total_students', models.IntegerField(default=0)),
                ('pending_clearances', models.IntegerField(default=0)),
                ('approved_clearances', models.IntegerField(default=0)),
                ('denied_clearances', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Program Chairs',
            },
        ),
        migrations.CreateModel(
            name='DashboardNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('program_chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programchair')),
            ],
        ),
    ]
