# Generated by Django 5.1.4 on 2025-02-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programchair',
            name='designation',
            field=models.CharField(choices=[('SET DEAN', 'School of Engineering and Technology (BSIT)'), ('STE DEAN', 'School of Teacher Education (BPED,BEED,BSED,BAELS,BSMATH)'), ('SOCJE DEAN', 'School of Criminal Justice Education (BSCRIM,BSISM)'), ('SAFES DEAN', 'School of Agriculture Forestry and Environmental Science (BSA,BSAES,BCF)')], max_length=50),
        ),
    ]
