# Generated by Django 5.1.5 on 2025-02-05 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_programchair_dashboardnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programchair',
            name='user',
        ),
        migrations.DeleteModel(
            name='DashboardNotification',
        ),
        migrations.DeleteModel(
            name='ProgramChair',
        ),
    ]
